[versions]
agp = "8.12.3"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
gServices = "4.4.4"
jetbrainsKotlinJvm = "2.3.0"
gDagger = "2.57.2"
activity = "1.12.2"
constraintlayout = "2.2.1"
aLottie = "6.7.1"
gGson = "2.13.2"
aLivedata = "2.10.0"
aViewModel = "2.10.0"
squareupRetrofit = "3.0.0"
squareupInterceptor = "5.3.2"
squareupGson = "3.0.0"
preference = "1.2.1"
security = "1.1.0"
agcp = "1.6.0.300"
playServicesLocation = "21.3.0" #Se usa esta version por el minsdk
hLocation = "6.9.0.300"
navigationFragmentKtxVersion = "2.9.6"
navigationUiKtxVersion = "2.9.6"
autodetection_ine = "1.0.0"
ellave = "1.0.3"
firebaseCrashlytics = "20.0.3"
firebaseConfig = "22.1.2"
firebaseAnalytics = "22.5.0"
firebaseCrashlyticsPlugin = "3.0.6"
sdk_pan = "1.2.0"
dependencyGuard = "0.5.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
com-airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "aLottie" }

google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gGson" }

androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "aLivedata" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "aViewModel" }

squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareupRetrofit" }
squareup-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "squareupInterceptor" }
squareup-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareupGson" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-security = { group = "androidx.security", name = "security-crypto", version.ref = "security" }
com-huawei-agconnect = { group = "com.huawei.agconnect",name = "agcp", version.ref = "agcp" }


play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
com-huawei-hms-location = { group = "com.huawei.hms", name = "location", version.ref = "hLocation" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }

firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-config-ktx = { group = "com.google.firebase", name = "firebase-config-ktx", version.ref = "firebaseConfig" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
iqsec-autodetectionine-ellave = { group = "mx.com.iqsec.auto_detection_ine", name = "ellave", version.ref = "autodetection_ine" }
iqsec-antispoffing-ellave = { group = "mx.com.iqsec.antispoffing", name = "ellave", version.ref = "ellave" }

iqsec-sdkpan-onboarding = { group = "mx.com.iqsec.sdkpan", name = "omboarding", version.ref = "sdk_pan" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gServices" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
googleDagger = { id = "com.google.dagger.hilt.android", version.ref = "gDagger" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
sonarqube = { id = "org.sonarqube", version = "3.5.0.2730" }
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }

#permiso de ejecucion
#chmod +x gradlew
# ./gradlew dependencyUpdates